"""
tests/test_tier3_convergence.py — Phase 3B Tier 3 Full Baseline
================================================================
The final convergence gate before translate() switches to the IR path.

Loads every KQL query from tests/tier3_queries.json (generated by
extract_tier3.py) and asserts that:

    normalize(SparkSQLGenerator(ast)) == normalize(IRSparkSQLGenerator(ir))

This is the same assertion as Tiers 1 and 2, now applied to the complete
353-query production baseline. Every query that passed the original
SparkSQLGenerator test suite must converge identically through the IR path.

Setup (run once):
    py tests/extract_tier3.py

Run all:
    py -m pytest tests/test_tier3_convergence.py -v

Run with failure detail:
    py -m pytest tests/test_tier3_convergence.py -v --tb=short

Track convergence rate:
    py -m pytest tests/test_tier3_convergence.py -q 2>&1 | tail -5

Convergence gate for Phase 3C (translate() flip):
    353/353 passing  +  Tiers 1+2 100%  +  Validator 100%  +  Snapshots 100%
"""

from __future__ import annotations

import json
import re
import sys
import os
from pathlib import Path

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'src'))

import pytest
from kqlbridge.parser import parse
from kqlbridge.generators.spark_sql import SparkSQLGenerator
from kqlbridge.ir import to_semantic_ir
from kqlbridge.ir.emitters.spark_ir import IRSparkSQLGenerator

TIER3_FILE = Path(__file__).parent / "tier3_queries.json"


# ─── SQL Normalizer (same as test_emitter_convergence.py) ────────────────────

def normalize_sql(sql: str) -> str:
    sql = re.sub(r'\s+', ' ', sql.strip())
    sql = sql.replace('<>', '!=')
    sql = sql.lower()
    sql = re.sub(r'\s*,\s*', ', ', sql)
    sql = re.sub(r'\s*=\s*', ' = ', sql)
    sql = re.sub(r'\s*!=\s*', ' != ', sql)
    sql = re.sub(r'\s+', ' ', sql).strip()
    return sql


# ─── Load queries ─────────────────────────────────────────────────────────────

def _load_tier3() -> list[dict]:
    if not TIER3_FILE.exists():
        return []
    return json.loads(TIER3_FILE.read_text(encoding="utf-8"))


TIER3_QUERIES = _load_tier3()


# ─── Guard: tier3_queries.json must exist ────────────────────────────────────

def test_tier3_file_exists():
    """
    tier3_queries.json must exist before Tier 3 tests run.
    If missing: py tests/extract_tier3.py
    """
    assert TIER3_FILE.exists(), (
        f"Tier 3 query file not found: {TIER3_FILE}\n"
        f"Generate it with: py tests/extract_tier3.py"
    )


def test_tier3_has_queries():
    """tier3_queries.json must contain at least 100 queries."""
    if not TIER3_FILE.exists():
        pytest.skip("tier3_queries.json not yet generated")
    queries = _load_tier3()
    assert len(queries) >= 100, (
        f"Expected >= 100 Tier 3 queries, found {len(queries)}.\n"
        f"Re-run: py tests/extract_tier3.py"
    )


def test_tier3_query_count():
    """Report the exact count — useful for convergence tracking."""
    if not TIER3_FILE.exists():
        pytest.skip("tier3_queries.json not yet generated")
    queries = _load_tier3()
    print(f"\nTier 3 query count: {len(queries)}")
    assert len(queries) > 0


# ─── Convergence core ─────────────────────────────────────────────────────────

def assert_tier3_converges(q_id: str, kql: str) -> None:
    """
    Core convergence assertion for Tier 3.
    Identical logic to Tiers 1 and 2 — same normalizer, same generators.
    """
    try:
        ast = parse(kql)
    except Exception as e:
        pytest.fail(f"[{q_id}] Parse failure: {e}\nKQL: {kql!r}")

    try:
        oracle_sql = SparkSQLGenerator().generate(ast)
    except Exception as e:
        pytest.fail(f"[{q_id}] Oracle generation failure: {e}\nKQL: {kql!r}")

    try:
        ir = to_semantic_ir(ast, validate=True)
    except Exception as e:
        pytest.fail(f"[{q_id}] IR transformation failure: {e}\nKQL: {kql!r}")

    try:
        candidate_sql = IRSparkSQLGenerator().emit(ir)
    except NotImplementedError as e:
        pytest.fail(
            f"[{q_id}] IR emitter missing primitive: {e}\n"
            f"KQL: {kql!r}\n"
            f"Add handling for this node type in spark_ir.py"
        )
    except Exception as e:
        pytest.fail(f"[{q_id}] IR emitter failure: {e}\nKQL: {kql!r}")

    oracle_norm = normalize_sql(oracle_sql)
    candidate_norm = normalize_sql(candidate_sql)

    assert oracle_norm == candidate_norm, (
        f"\n[{q_id}] Convergence MISMATCH\n"
        f"KQL:       {kql!r}\n"
        f"ORACLE:    {oracle_sql}\n"
        f"CANDIDATE: {candidate_sql}\n"
        f"ORACLE_N:  {oracle_norm}\n"
        f"CANDID_N:  {candidate_norm}"
    )


# ─── Parametrized Tier 3 tests ────────────────────────────────────────────────

@pytest.mark.parametrize(
    "q_id,kql",
    [(q["id"], q["kql"]) for q in TIER3_QUERIES],
    ids=[q["id"] for q in TIER3_QUERIES],
)
def test_tier3_convergence(q_id: str, kql: str):
    """
    Full 353-query convergence gate.

    Each test ID maps to one baseline KQL query from tier3_queries.json.
    All must pass before translate() switches to the IR path.

    If a group of failures shares a pattern (same operator, same structure),
    look at the corresponding _emit_*() method in spark_ir.py.
    """
    if not TIER3_FILE.exists():
        pytest.skip("tier3_queries.json not generated — run extract_tier3.py")
    assert_tier3_converges(q_id, kql)


# ─── Convergence report ───────────────────────────────────────────────────────

class TestConvergenceReport:
    """
    Scoreboard tests — not part of the gate, but useful for tracking progress.
    Run with -v -s to see the printout.
    """

    def test_print_convergence_rate(self, capsys):
        """
        Runs all Tier 3 queries and prints a convergence rate.
        Does NOT assert — informational only. Useful during Phase 3B repair work.

        Run: py -m pytest tests/test_tier3_convergence.py::TestConvergenceReport -v -s
        """
        if not TIER3_FILE.exists():
            pytest.skip("tier3_queries.json not generated")

        queries = _load_tier3()
        if not queries:
            pytest.skip("No Tier 3 queries found")

        passed = 0
        failed_ids: list[str] = []

        for q in queries:
            try:
                ast = parse(q["kql"])
                oracle = normalize_sql(SparkSQLGenerator().generate(ast))
                ir = to_semantic_ir(ast)
                candidate = normalize_sql(IRSparkSQLGenerator().emit(ir))
                if oracle == candidate:
                    passed += 1
                else:
                    failed_ids.append(q["id"])
            except Exception:
                failed_ids.append(q["id"])

        total = len(queries)
        rate = passed / total * 100 if total else 0

        with capsys.disabled():
            print(f"\n{'='*50}")
            print(f"  Tier 3 Convergence: {passed}/{total} ({rate:.1f}%)")
            if failed_ids:
                print(f"  Failed IDs: {failed_ids[:20]}")
                if len(failed_ids) > 20:
                    print(f"  ... and {len(failed_ids)-20} more")
            print(f"{'='*50}")

        # Always passes — this is a reporting test, not a gate
        assert True

    def test_print_failure_categories(self, capsys):
        """
        Groups failures by error type to identify systematic gaps.
        Run: py -m pytest tests/test_tier3_convergence.py::TestConvergenceReport::test_print_failure_categories -v -s
        """
        if not TIER3_FILE.exists():
            pytest.skip("tier3_queries.json not generated")

        queries = _load_tier3()
        categories: dict[str, list[str]] = {}

        for q in queries:
            try:
                ast = parse(q["kql"])
                oracle = normalize_sql(SparkSQLGenerator().generate(ast))
                ir = to_semantic_ir(ast)
                candidate = normalize_sql(IRSparkSQLGenerator().emit(ir))
                if oracle != candidate:
                    # Categorise by first differing token
                    oracle_words = oracle.split()
                    cand_words = candidate.split()
                    diff_pos = next(
                        (i for i, (a, b) in enumerate(zip(oracle_words, cand_words)) if a != b),
                        min(len(oracle_words), len(cand_words)),
                    )
                    context = (
                        oracle_words[diff_pos] if diff_pos < len(oracle_words) else "length_mismatch"
                    )
                    categories.setdefault(f"mismatch_at_{context}", []).append(q["id"])
            except NotImplementedError as e:
                categories.setdefault(f"NotImpl:{e}", []).append(q["id"])
            except Exception as e:
                categories.setdefault(f"Error:{type(e).__name__}", []).append(q["id"])

        with capsys.disabled():
            print(f"\n{'='*50}")
            print(f"  Tier 3 Failure Categories:")
            if not categories:
                print("  All queries converged!")
            for cat, ids in sorted(categories.items(), key=lambda x: -len(x[1])):
                print(f"  [{len(ids):3d}] {cat}")
                print(f"        First: {ids[0]}")
            print(f"{'='*50}")

        assert True
