from ..ast_nodes import KQLQuery, PipeOp, ProjectOp, WhereOp, SummarizeOp, ExtendOp, OrderOp, TakeOp
from .spark_sql import SparkSQLGenerator

class PySparkGenerator:
    """
    Experimental PySpark Generator.
    Routes KQL AST nodes to executable PySpark DataFrame Python code.
    """
    def __init__(self):
        self.sql_gen = SparkSQLGenerator()

    def generate(self, query: KQLQuery) -> str:
        """
        Main entry point for PySpark generation.
        """
        lines = []
        lines.append("import pyspark.sql.functions as F")
        lines.append("# Generated by KQLBridge PySparkGenerator")
        lines.append(f"df = spark.table('{query.table}')")
        
        for pipe in query.pipes:
            if isinstance(pipe, WhereOp):
                sql_cond = self.sql_gen._bool_expr(pipe.condition)
                lines.append(f"df = df.filter(\"{sql_cond}\")")
                
            elif isinstance(pipe, ProjectOp):
                cols = []
                for col in pipe.columns:
                    if pipe.aliases and col in pipe.aliases:
                        cols.append(f"\"{col} AS {pipe.aliases[col]}\"")
                    else:
                        cols.append(f"\"{col}\"")
                cols_str = ", ".join(cols)
                lines.append(f"df = df.selectExpr({cols_str})")
                
            elif isinstance(pipe, ExtendOp):
                exprs = []
                for alias, expr in pipe.assignments:
                    sql_expr = self.sql_gen._expr(expr)
                    exprs.append(f"\"{sql_expr} AS {alias}\"")
                cols_str = ", ".join(exprs)
                lines.append(f"df = df.selectExpr(\"*\", {cols_str})")
                
            elif isinstance(pipe, OrderOp):
                order_args = []
                for item in pipe.items:
                    col_sql = self.sql_gen._expr(item.col)
                    direction = "desc" if item.direction.lower() == "desc" else "asc"
                    order_args.append(f"F.expr(\"{col_sql}\").{direction}()")
                args_str = ", ".join(order_args)
                lines.append(f"df = df.orderBy({args_str})")
                
            elif isinstance(pipe, TakeOp):
                lines.append(f"df = df.limit({pipe.n})")
                
            elif isinstance(pipe, SummarizeOp):
                from ..ast_nodes import BinGroup, PlainGroup
                
                if pipe.group_by:
                    gb_cols = []
                    for gb in pipe.group_by:
                        if isinstance(gb, BinGroup):
                            col_sql = self.sql_gen._expr(gb.col)
                            gb_expr = self.sql_gen._render_bin(col_sql, gb.amount, gb.unit)
                            lines.append(f"df = df.withColumn(\"{col_sql}\", F.expr(\"{gb_expr}\"))")
                            gb_cols.append(f"\"{col_sql}\"")
                        elif isinstance(gb, PlainGroup):
                            col_sql = self.sql_gen._expr(gb.col)
                            gb_cols.append(f"\"{col_sql}\"")
                    
                    gb_str = ", ".join(gb_cols)
                    lines.append(f"df = df.groupBy({gb_str})")
                
                if pipe.aggregations:
                    agg_cols = []
                    for agg in pipe.aggregations:
                        sql_agg = self.sql_gen._agg(agg)
                        agg_cols.append(f"F.expr(\"{sql_agg}\")")
                    agg_str = ", ".join(agg_cols)
                    
                    lines.append(f"df = df.agg({agg_str})")
                    
            else:
                lines.append(f"# NotImplemented: {type(pipe).__name__}")
                
        lines.append("display(df)")
        return "\n".join(lines)
