from ..ast_nodes import (
    KQLQuery, PipeOp, ProjectOp, WhereOp, SummarizeOp, ExtendOp, OrderOp, TakeOp,
    DistinctOp, JoinOp, UnionOp, Negation, SubqueryInExpr, CountOp, SerializeOp
)
from .spark_sql import SparkSQLGenerator
from typing import Optional

class PySparkGenerator:
    """
    Experimental PySpark Generator.
    Routes KQL AST nodes to executable PySpark DataFrame Python code.
    """
    def __init__(self):
        self.sql_gen = SparkSQLGenerator()

    def generate(self, query: KQLQuery) -> str:
        """
        Main entry point for PySpark generation.
        """
        lines = []
        lines.append("import pyspark.sql.functions as F")
        lines.append("# Generated by KQLBridge PySparkGenerator")
        
        self.sql_gen._scalar_bindings = {}
        let_names = {binding.name for binding in query.let_bindings}
        
        # Main query DataFrame
        lines.extend(self._generate_query(query, "df", let_names))
        lines.append("display(df)")
        return "\n".join(lines)

    def _extract_subqueries(self, expr) -> list[tuple[SubqueryInExpr, bool]]:
        from ..ast_nodes import Negation, LogicalOp, SubqueryInExpr
        
        if isinstance(expr, SubqueryInExpr):
            return [(expr, False)]
        elif isinstance(expr, Negation):
            subqueries = self._extract_subqueries(expr.expr)
            return [(sub, not neg) for sub, neg in subqueries]
        elif isinstance(expr, LogicalOp):
            if expr.op.lower() == "and":
                return self._extract_subqueries(expr.left) + self._extract_subqueries(expr.right)
        return []

    def _remove_subqueries(self, expr):
        from ..ast_nodes import Negation, LogicalOp, SubqueryInExpr
        
        if isinstance(expr, SubqueryInExpr):
            return None
        elif isinstance(expr, Negation):
            inner = self._remove_subqueries(expr.expr)
            if inner is None:
                return None
            return Negation(inner)
        elif isinstance(expr, LogicalOp):
            left = self._remove_subqueries(expr.left)
            right = self._remove_subqueries(expr.right)
            if left is None:
                return right
            if right is None:
                return left
            return LogicalOp(left, expr.op, right)
        return expr

    def _generate_query(self, query: KQLQuery, df_name: str, let_names: set[str]) -> list[str]:
        lines = []
        
        # Merge local let bindings into let_names
        local_let_names = set(let_names)
        if query.let_bindings:
            for binding in query.let_bindings:
                if hasattr(binding.value, "scalar_expr"):
                    self.sql_gen._scalar_bindings[binding.name] = binding.value.scalar_expr
                    continue
                local_let_names.add(binding.name)
                # Generate the let binding query
                lines.extend(self._generate_query(binding.value, binding.name, local_let_names))
                lines.append("")  # blank line for readability
                
        if query.table in local_let_names:
            lines.append(f"{df_name} = {query.table}")
        else:
            lines.append(f"{df_name} = spark.table('{query.table}')")
        
        for pipe in query.pipes:
            if isinstance(pipe, WhereOp):
                subqueries = self._extract_subqueries(pipe.condition)
                
                # Apply all extracted subquery joins first
                for sub_expr, is_negated in subqueries:
                    col_name = self.sql_gen._expr(sub_expr.col)
                    subquery_df = f"subquery_{col_name}"
                    subquery_lines = self._generate_query(sub_expr.subquery, subquery_df, local_let_names)
                    lines.extend(subquery_lines)
                    
                    join_type = "left_anti" if (sub_expr.negated ^ is_negated) else "left_semi"
                    lines.append(f"{df_name} = {df_name}.join({subquery_df}, on='{col_name}', how='{join_type}')")
                
                # Apply remaining filters
                rem_expr = self._remove_subqueries(pipe.condition)
                if rem_expr is not None:
                    sql_cond = self.sql_gen._bool_expr(rem_expr)
                    lines.append(f"{df_name} = {df_name}.filter(\"{sql_cond}\")")
                    
            elif isinstance(pipe, ProjectOp):
                cols = []
                for col in pipe.columns:
                    if pipe.aliases and col in pipe.aliases:
                        cols.append(f"\"{col} AS {pipe.aliases[col]}\"")
                    else:
                        cols.append(f"\"{col}\"")
                cols_str = ", ".join(cols)
                lines.append(f"{df_name} = {df_name}.selectExpr({cols_str})")
                
            elif isinstance(pipe, ExtendOp):
                exprs = []
                for alias, expr in pipe.assignments:
                    sql_expr = self.sql_gen._expr(expr)
                    exprs.append(f"\"{sql_expr} AS {alias}\"")
                cols_str = ", ".join(exprs)
                lines.append(f"{df_name} = {df_name}.selectExpr(\"*\", {cols_str})")
                
            elif isinstance(pipe, OrderOp):
                order_args = []
                for item in pipe.items:
                    col_sql = self.sql_gen._expr(item.col)
                    direction = "desc" if item.direction.lower() == "desc" else "asc"
                    order_args.append(f"F.expr(\"{col_sql}\").{direction}()")
                args_str = ", ".join(order_args)
                lines.append(f"{df_name} = {df_name}.orderBy({args_str})")
                
            elif isinstance(pipe, TakeOp):
                lines.append(f"{df_name} = {df_name}.limit({pipe.n})")
                
            elif isinstance(pipe, DistinctOp):
                if pipe.columns and pipe.columns != ["*"]:
                    cols_str = ", ".join(f"\"{col}\"" for col in pipe.columns)
                    lines.append(f"{df_name} = {df_name}.selectExpr({cols_str}).distinct()")
                else:
                    lines.append(f"{df_name} = {df_name}.distinct()")
                    
            elif isinstance(pipe, JoinOp):
                if not pipe.keys:
                    raise ValueError("Join keys must be specified for PySpark Join operation.")
                right_df = f"join_right_{pipe.keys[0]}"
                right_lines = self._generate_query(pipe.right, right_df, local_let_names)
                lines.extend(right_lines)
                kind = pipe.kind or "inner"
                lines.append(f"{df_name} = {df_name}.join({right_df}, on={pipe.keys}, how='{kind}')")
                
            elif isinstance(pipe, UnionOp):
                for idx, table in enumerate(pipe.tables):
                    if pipe.subqueries and table in pipe.subqueries:
                        union_df = f"union_df_{idx}"
                        sub_lines = self._generate_query(pipe.subqueries[table], union_df, local_let_names)
                        lines.extend(sub_lines)
                        lines.append(f"{df_name} = {df_name}.unionByName({union_df}, allowMissingColumns=True)")
                    elif table in local_let_names:
                        lines.append(f"{df_name} = {df_name}.unionByName({table}, allowMissingColumns=True)")
                    else:
                        union_df = f"union_df_{idx}"
                        lines.append(f"{union_df} = spark.table('{table}')")
                        lines.append(f"{df_name} = {df_name}.unionByName({union_df}, allowMissingColumns=True)")
                    
            elif isinstance(pipe, SummarizeOp):
                from ..ast_nodes import BinGroup, PlainGroup
                
                if pipe.group_by:
                    gb_cols = []
                    for gb in pipe.group_by:
                        if isinstance(gb, BinGroup):
                            col_sql = self.sql_gen._expr(gb.col)
                            gb_expr = self.sql_gen._render_bin(col_sql, gb.amount, gb.unit)
                            lines.append(f"{df_name} = {df_name}.withColumn(\"{col_sql}\", F.expr(\"{gb_expr}\"))")
                            gb_cols.append(f"\"{col_sql}\"")
                        elif isinstance(gb, PlainGroup):
                            col_sql = self.sql_gen._expr(gb.col)
                            gb_cols.append(f"\"{col_sql}\"")
                    
                    gb_str = ", ".join(gb_cols)
                    lines.append(f"{df_name} = {df_name}.groupBy({gb_str})")
                
                if pipe.aggregations:
                    agg_cols = []
                    for agg in pipe.aggregations:
                        sql_agg = self.sql_gen._agg(agg)
                        agg_cols.append(f"F.expr(\"{sql_agg}\")")
                    agg_str = ", ".join(agg_cols)
                    
                    lines.append(f"{df_name} = {df_name}.agg({agg_str})")
                    
            elif isinstance(pipe, CountOp):
                lines.append(f"{df_name} = {df_name}.agg(F.expr(\"COUNT(*) AS count_\"))")
                
            elif isinstance(pipe, SerializeOp):
                pass
                
            else:
                lines.append(f"# NotImplemented: {type(pipe).__name__}")
                
        return lines
