"""
ir/emitters/pyspark_ir.py — IR-Driven PySpark DataFrame Emitter
===============================================================
Phase 4C. Reads a SemanticQuery IR envelope and produces PySpark
DataFrame transformation chains instead of SQL strings.

Design:
  - Output is a Python code string representing PySpark DataFrame API chains.
  - Reuses the robust, proven expression/bool/aggregation rendering from IRSparkSQLGenerator
    via lightweight SQL extraction embedded directly in DataFrame API arguments.
  - Implements Single Static Assignment (SSA) style variable indexing for joins/unions
    to prevent sibling DataFrame scope clobbering.
"""

from __future__ import annotations
import re
from typing import List, Optional

from ..nodes import (
    SemanticQuery, SemanticFilter, SemanticProjection, ProjectionItem,
    SemanticAggregate, AggregateItem, SemanticJoin, SemanticUnion,
    SemanticExpression, SemanticColumnRef, SemanticLiteral, SemanticFunctionCall,
)
from .spark_ir import IRSparkSQLGenerator


class IRPySparkGenerator:
    """
    Emits PySpark DataFrame code by walking a SemanticQuery IR envelope.
    """

    def __init__(self, hint=None, options=None):
        self.hint = hint
        # Initialize nested SQL emitter to reuse its robust expression/bool translation
        self.sql_emitter = IRSparkSQLGenerator(hint=hint, options=options)

    def emit(self, ir: SemanticQuery) -> str:
        """
        Main entrypoint. Generates a Python code block.
        CTEs become named DataFrames, referenced inline.
        """
        self._let_names = set(ir.ctes.keys())
        self._join_index = 0
        self._union_index = 0

        lines: list[str] = ["import pyspark.sql.functions as F", "# Generated by KQLBridge IRPySparkGenerator"]

        # Generate CTE DataFrames first
        for cte_name, cte_ir in ir.ctes.items():
            cte_lines = self._emit_steps(cte_ir, df_name=cte_name)
            lines.extend(cte_lines)
            lines.append("")

        # Main query DataFrame (df)
        body_lines = self._emit_steps(ir, df_name="df")
        lines.extend(body_lines)
        lines.append("display(df)")
        return "\n".join(lines)

    def _emit_steps(self, ir: SemanticQuery, df_name: str) -> list[str]:
        """
        Walk IR steps and emit sequential DataFrame assignments.
        """
        lines = []
        if ir.source_table in self._let_names:
            lines.append(f"{df_name} = {ir.source_table}")
        else:
            lines.append(f"{df_name} = spark.table('{ir.source_table}')")

        for step in ir.steps:
            from ...plugins import get_renderer
            custom_renderer = None
            if getattr(step, "origin_node", None) is not None:
                custom_renderer = get_renderer(type(step.origin_node), "pyspark")
            
            if custom_renderer:
                res_line = custom_renderer(self, step.origin_node, df_name)
                if isinstance(res_line, list):
                    lines.extend(res_line)
                else:
                    lines.append(f"{df_name} = {res_line}")
                continue

            if isinstance(step, SemanticFilter):
                sql_cond = self.sql_emitter._bool_expr(step.predicate, is_top_level=True)
                lines.append(f"{df_name} = {df_name}.filter(\"{sql_cond}\")")

            elif isinstance(step, SemanticProjection):
                if step.is_extend_only:
                    ext_parts = []
                    for item in step.items:
                        if item.origin_node is not None:
                            sql_expr = self.sql_emitter._expr(item.expression)
                            ext_parts.append(f"\"{sql_expr} AS {item.alias}\"")
                    cols_str = ", ".join(ext_parts)
                    lines.append(f"{df_name} = {df_name}.selectExpr(\"*\", {cols_str})")
                else:
                    proj_parts = []
                    for item in step.items:
                        sql_expr = self.sql_emitter._expr(item.expression)
                        if isinstance(item.expression, SemanticColumnRef) and item.expression.name == item.alias:
                            proj_parts.append(f"\"{item.alias}\"")
                        else:
                            proj_parts.append(f"\"{sql_expr} AS {item.alias}\"")
                    cols_str = ", ".join(proj_parts)
                    lines.append(f"{df_name} = {df_name}.selectExpr({cols_str})")

            elif isinstance(step, SemanticAggregate):
                if step.group_by:
                    gb_cols = []
                    for gb in step.group_by:
                        if isinstance(gb.expression, SemanticFunctionCall) and gb.expression.name == "bin":
                            col_sql = self.sql_emitter._expr(gb.expression.arguments[0])
                            val_str = gb.expression.arguments[1].value if isinstance(gb.expression.arguments[1], SemanticLiteral) else str(gb.expression.arguments[1])
                            m = re.match(r"(\d+)([a-zA-Z]+)", val_str.strip())
                            amount = int(m.group(1)) if m else 1
                            unit = m.group(2) if m else "d"
                            gb_expr = self.sql_emitter._render_bin(col_sql, amount, unit)
                            lines.append(f"{df_name} = {df_name}.withColumn(\"{col_sql}\", F.expr(\"{gb_expr}\"))")
                            gb_cols.append(f"\"{col_sql}\"")
                        else:
                            col_sql = self.sql_emitter._expr(gb.expression)
                            gb_cols.append(f"\"{col_sql}\"")
                    gb_str = ", ".join(gb_cols)
                    lines.append(f"{df_name} = {df_name}.groupBy({gb_str})")

                if step.aggregations:
                    agg_cols = []
                    for agg in step.aggregations:
                        if agg.origin_node is not None:
                            sql_agg = self.sql_emitter._agg(agg.origin_node)
                        else:
                            sql_agg = f"{agg.function_name.upper()}(*) AS {agg.alias}"
                        agg_cols.append(f"F.expr(\"{sql_agg}\")")
                    agg_str = ", ".join(agg_cols)
                    lines.append(f"{df_name} = {df_name}.agg({agg_str})")

            elif isinstance(step, SemanticJoin):
                # Match AST-based PySparkGenerator naming: join_right_{first_key}
                first_key = step.conditions[0].left_col if step.conditions else "key"
                right_df = f"join_right_{first_key}"
                right_lines = self._emit_steps(step.right_query, right_df)
                lines.extend(right_lines)
                
                keys = [cond.left_col for cond in step.conditions]
                kind = step.kind or "inner"
                lines.append(f"{df_name} = {df_name}.join({right_df}, on={keys}, how='{kind}')")

            elif isinstance(step, SemanticUnion):
                # Walk union branches using 0-based branch index (union_df_0, union_df_1, etc.)
                for idx, branch in enumerate(step.inputs):
                    union_df = f"union_df_{idx}"
                    if branch.steps:
                        sub_lines = self._emit_steps(branch, union_df)
                        lines.extend(sub_lines)
                    else:
                        if branch.source_table in self._let_names:
                            lines.append(f"{union_df} = {branch.source_table}")
                        else:
                            lines.append(f"{union_df} = spark.table('{branch.source_table}')")
                    lines.append(f"{df_name} = {df_name}.unionByName({union_df}, allowMissingColumns=True)")

        # Apply pipeline_state
        ps = ir.pipeline_state
        if "order_by" in ps:
            order_args = []
            for item in ps["order_by"]:
                col = item["column"]
                direction = item["direction"].lower()
                col_sql = self.sql_emitter._expr(col) if not isinstance(col, str) else col
                order_args.append(f"F.expr(\"{col_sql}\").{direction}()")
            args_str = ", ".join(order_args)
            lines.append(f"{df_name} = {df_name}.orderBy({args_str})")
        if "limit" in ps:
            lines.append(f"{df_name} = {df_name}.limit({ps['limit']})")
        distinct_info = ps.get("distinct")
        if distinct_info:
            if distinct_info.get("columns") and distinct_info["columns"] != ["*"]:
                cols_str = ", ".join(f"\"{col}\"" for col in distinct_info["columns"])
                lines.append(f"{df_name} = {df_name}.selectExpr({cols_str}).distinct()")
            else:
                lines.append(f"{df_name} = {df_name}.distinct()")
        if ps.get("count"):
            lines.append(f"{df_name} = {df_name}.agg(F.expr(\"COUNT(*) AS count_\"))")

        return lines
